const NAME_BODY_PARAMETER = "name"
const LAST_NAME_BODY_PARAMETER = "lastname"
const PHONE_NUMBER_BODY_PARAMETER = "phoneNumber"
const EMAIL_BODY_PARAMETER = "email"
const USERNAME_BODY_PARAMETER = "username"
const PASSWORD_BODY_PARAMETER = "password"
const CONFIRMATION_CODE_BODY_PARAMETER = "confirmationCode"
const AWS_COGNITO_SESSION_PARAMETER = "Session"
const AWS_COGNITO_PHONE_NUMBER_PARAMETER = "phone_number"
const AWS_COGNITO_FAMILY_NAME_PARAMETER = "family_name"
const AWS_COGNITO_GIVEN_NAME_PARAMETER = "given_name"
const AWS_COGNITO_USERNAME_PARAMETER = "USERNAME"
const AWS_COGNITO_PASSWORD_PARAMETER = "PASSWORD"
const SESSION_EXCEPTION_ID = "SessionIsNull"
const PHONE_NUMBER_CONFLICT = "PHONE_NUMBER_CONFLICT"

module.exports = {
    NAME_BODY_PARAMETER,
    LAST_NAME_BODY_PARAMETER,
    PHONE_NUMBER_BODY_PARAMETER,
    EMAIL_BODY_PARAMETER,
    USERNAME_BODY_PARAMETER,
    PASSWORD_BODY_PARAMETER,
    CONFIRMATION_CODE_BODY_PARAMETER,
    AWS_COGNITO_SESSION_PARAMETER,
    AWS_COGNITO_PHONE_NUMBER_PARAMETER,
    AWS_COGNITO_FAMILY_NAME_PARAMETER,
    AWS_COGNITO_GIVEN_NAME_PARAMETER,
    SESSION_EXCEPTION_ID,
    PHONE_NUMBER_CONFLICT,
    AWS_COGNITO_USERNAME_PARAMETER,
    AWS_COGNITO_PASSWORD_PARAMETER
}
